---
name: "Shellcheck"

on:
  push:
    branches: ["master"]
    paths: ["**/*.sh"]
  pull_request:
    paths: ["**/*.sh"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    name: "Run shellcheck"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Run shellcheck"
        uses: ludeeus/action-shellcheck@master
